### ISSUE TITLE
Renaming a part results in two copies in the toolbox

### ISSUE THREAD

**Issue by keithclark** [KanoComputing/kano-code#1804]
Renaming a Part in the part list causes the toolbox sidebar to show two copies of it, one with the new name and a second with the old name. You can see this in the screenshot below:

![2020-01-12-221831_653x624_scrot](https://user-images.githubusercontent.com/588665/72226572-6c7b4b80-358a-11ea-935c-faadeecba8ea.png)

Steps to recreate: 

1) Add a new part (I used a Speaker)
2) Rename the part (I used "Speaker 2").
3) Note the two copies in the sidebar.

Once the rename step is complete, it's no longer possible to delete the part having the original name. It's also not possible to perform another rename as the browser throws an error.

**Comment by pazdera** [comment]
Also included in [v3.0.1-alpha.21](https://www.npmjs.com/package/@kano/code) and should land on Kano World with the next release. Thank you!

**Comment by keithclark** [comment]
When will this be available in Kano World?
