### ISSUE TITLE
Accidental triggering of context menu

### ISSUE THREAD

**Issue by keithclark** [KanoComputing/kano-code#1805]
Right clicking outside the block editor area shows the native browser context menu, which my child is finding frustrating as it's too easy trigger accidentally do with the trackpad on the Kano Computer Kit keyboard.

Is it possible to disable the menu to prevent accidental navigation or reloading of the page?

**Comment by pazdera** [comment]
Good point. We already disable the context menu for the electron builds of Kano Code. It would make sense to do it here as well.

I'll run this by the PM to see what they think.

**Comment by pazdera** [comment]
Thinking about this, it would be good to let the consumer of this library decide whether they want the context menu or not which can be done with something like:

```js
editorInstance.onDidInject(() => {
    editorInstance.domNode.addEventListener('contextmenu', e => e.preventDefault());
});
```
So I'll leave it on by default in the library. But I've disabled it in the parent Kano World codebase, and it is schedule to come out with the next release.

Thanks for reporting this, @keithclark.

**Comment by keithclark** [comment]
👍 Thanks for fixing this. It's a small change, but it'll make for a less frustrating user experience.

I suspected disabling this in Kano World might be the answer (because it's *really* annoying when a library imposes its will on the environment its used in). 

Unfortunately, I don't have any visibility on Kano World so couldn't create an issue/PR for it, hence raising the issue here.
