### ISSUE TITLE
Parts can be renamed to values that throw errors

### ISSUE THREAD

**Issue by keithclark** [KanoComputing/kano-code#1806]
Part names can be renamed to begin with numbers or set to an empty string, which causes the browser to throw errors and prevents creations from working with no feedback for the user. Opening devtools reveals the issue:

![2020-01-12-223900_653x662_scrot](https://user-images.githubusercontent.com/588665/72226753-6a19f100-358c-11ea-9142-27a771c02804.png)

To recreate:

1) Open devtools, clear error logs.
2) Add a part
3) Drag the part into the code editor
4) Rename the part to "1"
5) Review devtools console.

**Comment by pazdera** [comment]
Included in [v3.0.1-alpha.21](https://www.npmjs.com/package/@kano/code). It should land on Kano World with the next release.

Thanks!
