### ISSUE TITLE
Use creation name for the filename when exporting an app

### ISSUE THREAD

**Issue by keithclark** [KanoComputing/kano-code#1807]
When exporting a creation, the browser downloads the file as `my-app(1).kcode`, with (1) indicating the copy number.  Once a creation has been exported, users have to find the file in the filesystem and rename it so something that reflects the creation they are working on so they can find it later.

Could the creation name (set in the top bar) be used to generate the file name? This would prevent users from needing to browse the file system to name their creations.

**Comment by pazdera** [comment]
Makes sense 👍. I'll see when we can get this in.

Thanks for the suggestion!

**Comment by pazdera** [comment]
I added an option to customise the name when calling export (see #1817). And I wired that to the title as you suggested in our parent codebase. It'll be out on Kano World with the other changes hopefully soon.

Thanks again!
