### ISSUE TITLE
https://code-docs.kano.me/ link is broken

### ISSUE THREAD

**Issue by explorigin** [KanoComputing/kano-code#1862]
**Describe the bug**
I was looking at setting up kano-code locally so I clicked on the docs link (https://code-docs.kano.me/)

I get:
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>7A369AB8A57B3E67</RequestId>
<HostId>
YBocTofPGTCR5fVrMYgEYqbH0DHpXTs5cfM/fXEu5RgqUblk0R/byQnIaPv5rSQS3vbTGodj/NY=
</HostId>
</Error>```

**Comment by onishiweb** [comment]
Hi @explorigin,

After looking into it, it looks like recent releases have mostly been prereleases which may be the cause of the issue, you can now find the docs at: https://code-docs.kano.me/3.0.1-alpha.49/index.html 

I've updated the `setup.md` docs in the repo (#1863) to reflect the change in URL and we'll aim to keep this updated if/when we release in the future.

Thanks for raising the issue and letting us know.
